name: Bicep Template Build and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      securelab: ${{ steps.filter.outputs.securelab }}
      accpmk: ${{ steps.filter.outputs.accpmk }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          securelab:
            - '10-Secure-Lab-Environment/AKV-DES-CMK/Private-AKV/Bicep/*'
          accpmk:
            - '00-ACC-VM-Loop/Platform-Key/Bicep/*'


  secure_build_and_test:
    needs: changes
    if: ${{ needs.changes.outputs.securelab == 'true' }}
    name: Secure Lab Bicep Build and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Run Bicep build
      uses: aliencube/bicep-build-actions@v0.1
      with:
        files: '10-Secure-Lab-Environment/AKV-DES-CMK/Private-AKV/Bicep/main.bicep'

    - name: Run ARM TTK
      uses: aliencube/arm-ttk-actions@v0.3
      id: armtest
      with:
        path: ./10-Secure-Lab-Environment/AKV-DES-CMK/Private-AKV/Bicep/main.json

    - name: Show ARM TTK test result
      shell: bash
      continue-on-error: true
      run: |
        echo 'Results: ${{ toJSON(fromJSON(steps.armtest.outputs.results)) }}'    

  accpmk_build_and_test:
    needs: changes
    if: ${{ needs.changes.outputs.accpmk == 'true' }}
    name: ACCPMK Bicep Build and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Run Bicep build
      uses: aliencube/bicep-build-actions@v0.1
      with:
        files: '00-ACC-VM-Loop/Platform-Key/Bicep/main.bicep'

    - name: Run ARM TTK
      uses: aliencube/arm-ttk-actions@v0.3
      id: armtest
      with:
        path: ./00-ACC-VM-Loop/Platform-Key/Bicep/main.json

    - name: Show ARM TTK test result
      shell: bash
      continue-on-error: true
      run: |
        echo 'Results: ${{ toJSON(fromJSON(steps.armtest.outputs.results)) }}'   